# TODO: auto generate from the values.yaml or better options? 
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuazhzIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IjgwMzAyMTc1IiwiYXV0aCI6IllXUnRhVzQ2T0RBek1ESXhOelU9In19fQ==
kind: Secret
metadata:
  name: {{ .Values.dockerSecretName }}
  namespace: {{ .Values.namespace }}
  # annotations:
  #   "helm.sh/resource-policy": keep
type: kubernetes.io/dockerconfigjson
