apiVersion: v1
kind: Secret
# data:
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-msa-account-mirror
  annotations:
     reflector.v1.k8s.emberstack.com/reflected-version: ""
     reflector.v1.k8s.emberstack.com/reflects: "default/source-msa-account-secret"
type: Opaque
