apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ .Values.frontEnd.name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
