---
# update to ingress if Layer4 is available nginx 1.17
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontEnd.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.frontEnd.name }}
  # type: LoadBalancer
  ports: 
    - protocol: TCP
      port: {{ .Values.frontEnd.servicePort }}
      targetPort: 8080    # changed due to new nginx